### ISSUE TITLE
It renders!

### ISSUE THREAD

**Issue by Nowosad** [geocompx/geocompjl#1]
https://geocompx.github.io/geocompjl/

(Messy) GHA: https://github.com/geocompx/geocompjl/blob/main/.github/workflows/main.yaml

Related Docker: https://github.com/geocompx/docker/blob/master/julia/Dockerfile

CC: @rafaqz, @evetion

**Comment by Nowosad** [comment]
@evetion -- the one issue I do not understand, it that I am getting a Julia image with version 1.11, but then I still need to install julia with apt (version 1.05). Otherwise julia is not available on GHA.

**Comment by rafaqz** [comment]
Packages managers are not great for Julia. But theres is a github action to add it like this:

https://github.com/rafaqz/Rasters.jl/blob/aa7164bd1f79609a0b5946bf338f4145de7191e5/.github/workflows/ci.yml#L25C16-L25C43

**Comment by Nowosad** [comment]
@rafaqz Feel free to update/replace the current GHA settings

**Comment by evetion** [comment]
Tried my hand at it in main

**Comment by Robinlovelace** [comment]
Cool!

**Comment by evetion** [comment]
Ok, removed the Docker and all used official Github actions for now. Pretty fast as well. Thanks for setting this up ❤️
