### ISSUE TITLE
Book cover (placeholder)

### ISSUE THREAD

**Issue by Nowosad** [geocompx/geocompjl#11]
It is usually good to have a placeholder for the book cover (to put it on a website, presentations, etc.). 

Atm, I think, this is of a low priority, but it would be good to have one some day.

**Comment by asinghvi17** [comment]
Definitely!  It would be great if we generated the cover with Julia code that also lives in the repo :) - will look into it (but it'll probably take at least a few months).

**Comment by evetion** [comment]
This should be fun, let me generate something quickly with GeoMakie.
