### ISSUE TITLE
GHA

### ISSUE THREAD

**Issue by Nowosad** [geocompx/geocompjl#12]
@evetion each push to the main takes about 8 minutes to render on GHA. I think this is mostly due to the installation of the julia packages that happens each time ("Installing known registries into `~/.julia`). Is it possible to make it faster (e.g., cache the installed packages, etc.)?

**Comment by evetion** [comment]
I will take a look into it. Are we GHA limited?

**Comment by Nowosad** [comment]
Are you asking if we can use some other CI/CD? My experience is mostly in GHA. 

(Context: the book is published on jl.geocompx.org based on the changes in the gh-pages branch of this repo. Thus, currently, when you push to the main, it starts GHA -> the book is built on the gh-pages branch -> the book is rendered on jl.geocompx.org)

**Comment by evetion** [comment]
Fixed with https://github.com/geocompx/geocompjl/commit/e913adfe72d7c872a993253c1c0e350f197c629a (and caching stuff in the commit before it)
